### ISSUE TITLE
Create function to return contract meta data object and remove all one off getter functions

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#111]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

*Summary*: Adding a getter function for each piece of contract meta data causes alot of uneeded lookups and extra function calls

### Description
*Type*:  Feature

### Current Behavior
We have MANY getter functions for contract meta data

### Expected Behavior
We have one getter function for a contract meta data object

### Definition of Done
- [ ] create a `MarketProtocolContractMetaData` object
- [ ] create a `MarketProtocolOraclizeContractMetaData` object that extends `MarketProtocolContractMetaData` with needed fields unique to MarketContractOraclize
- [ ] create a getter function that creates these objects in Market.ts
- [ ] add tests for all code created.
- [ ] remove all now redundanty `get` methods for contract meta data and update tests. 

### Additional Information
cc @rojosnow - thoughts on this approach to solve all your getters?
