### ISSUE TITLE
Return values from all transactions 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#88]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a dev using MARKET.js returning a promise<txHash> rather than a value after a transaction has been mined is probably more useful

### Why Is this Needed?
*Summary*: mining could take a very very long time

### Description
*Type*: Feature

### Current Behavior
We aren't always returning a txHash (see traderOrderAsync for example)

### Expected Behavior
for any transaction, we return a promise<string> with the txHash

### Definition of Done

- [ ] implement promise<string> return values
- [ ] fix all tests (big issue)
- [ ] implement new methods for getting results of important txs (for instance tradedQty from tradeOrderAsync)

**Comment by perfectmak** [comment]
Is this still relevant?

**Comment by pelsasser** [comment]
Nope!
